### ISSUE TITLE
Coverage analysis fails

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#104]
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0
:report (default-cli) on project java-design-patterns: I/O operation failed: No
source found for domainapp/dom/modules/simple/QSimpleObject.java -> [Help 1]

**Comment by iluwatar** [comment]
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:3.1.0
:report (default-cli) on project java-design-patterns: Build error: 32 -> [Help
1]

**Comment by trautonen** [comment]
Coveralls plugin fails because it cannot handle equally named classes in a multi-module project. There are at least three modules containing class `com.iluwatar.App` and the plugin fails to select a correct one for a coverage report. This is known defect in the plugin, but really hard to solve. Version 3.2.0 of the plugin will improve the error message of such cases so it's easier to detect, but still no real solution for the issue.

To get the coveralls reports correctly, make sure there are no same fully qualified class names between the modules. For example add a package suffix for each module. I think most of the modules follow this naming pattern already.

**Comment by iluwatar** [comment]
Thank you for looking into the problem. I will take your hint and make sure the classes have different fully qualified domain names. This is related to issue #108
