### ISSUE TITLE
CQRS pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#105]
http://martinfowler.com/bliki/CQRS.html

**Comment by amit2103** [comment]
@iluwatar @npathai Will like to implement this. Though this will take a bit of time.

**Comment by iluwatar** [comment]
Ok great, I'll update the issue labels.

**Comment by iluwatar** [comment]
@amit2103 any updates?

**Comment by amit2103** [comment]
@iluwatar  Will start working this week

**Comment by khajavi** [comment]
+۱

**Comment by iluwatar** [comment]
https://msdn.microsoft.com/en-us/library/dn568103.aspx

**Comment by iluwatar** [comment]
http://blog.eisele.net/2016/07/cqrs-with-java-and-lagom.html

**Comment by iluwatar** [comment]
This issue is free for taking again.

**Comment by inbravo** [comment]
https://github.com/AxonFramework/AxonFramework is based on CQRS

**Comment by iluwatar** [comment]
http://cloud.rohitkelapure.com/2016/10/cqrs-and-event-sourcing-in-java-with.html

**Comment by isabiq** [comment]
Hello, can I take this one?

**Comment by iluwatar** [comment]
Ok @isabiq

**Comment by alonsoir** [comment]
Where is the asynchronous message exchanger that connects the command manager with the query manager? Shouldn't the command manager be an event engine? Come on, let the commands be saved as events rather than as tuples in a relational engine. On the query manager side, it should listen to the asynchronous message broker to feed this part of the architecture so that both sides are synchronized, right?

**Comment by isabiq** [comment]
Hi, to answer your questions you can take a look at [Greg Young - CQRS, Task Based UIs, Event Sourcing agh!](http://codebetter.com/gregyoung/2010/02/16/cqrs-task-based-uis-event-sourcing-agh/).
