### ISSUE TITLE
Parameterized Specification

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1055]
Specification pattern example shows simple use of hard-coded specifications. To add another specification one needs to edit the code and add new class for it.

In this task we extend the example so that "parameterized specification" is also demonstrated. It is described in mr. Fowler's paper as specification that can be built without programming.

Links:
https://martinfowler.com/apsupp/spec.pdf
https://java-design-patterns.com/patterns/specification/
https://github.com/iluwatar/java-design-patterns/tree/master/specification

**Comment by MaVdbussche** [comment]
I would like to work on this issue if it is still available.

**Comment by iluwatar** [comment]
Go ahead @MaVdbussche

**Comment by MaVdbussche** [comment]
I have written the code, the tests and updated the README, but I need help when it comes to the UML diagram. How should i proceed to update it ? Am I correct in assuming that the .ucls file dynamically generates a .png image representing the class diagram ? I understand that this file should be edited from an Eclipse plugin; are you aware of any other way to edit it ?
I am of course open to the idea of installing Eclipse if necessary; I was just wondering if you knew any other way to edit this file, since my Google research was unsuccessful.

Many thanks !

**Comment by iluwatar** [comment]
Yes, we currently use the Eclipse plugin to create the class diagram. I'm not aware of alternate methods, it has to be used from Eclipse IDE. However, if the class diagram is missing it doesn't prevent accepting the pull request. We can add the class diagram later. In the future I'm hoping to integrate https://github.com/iluwatar/uml-reverse-mapper to generate the class diagrams from code automatically.

**Comment by MaVdbussche** [comment]
@iluwatar I have created a PR for this issue at https://github.com/iluwatar/java-design-patterns/pull/1088. Please do not hesitate to give me your feedback on it :)
