### ISSUE TITLE
Logging in API Gateway

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#1338]
At the moment api-gateway pattern does not use a proper logger as in other examples. In this issue we fix that.

**Comment by amit1307** [comment]
I can work on it, if you would like it to assign it to me?

**Comment by iluwatar** [comment]
Thanks @amit1307 please go ahead

**Comment by amit1307** [comment]
Hey, I was trying to start on this one but might need some more info if that's okay.

My understanding of this issue is that we don't have any logger configured for `api-gateway` but after it seems like there is nothing logged at all by any modules under `api-gateway`. So is the requirement here is to add logger as well as the logs or just the logger? Could you please clarify that?

**Comment by iluwatar** [comment]
True, there's only a couple of `e.printStackTrace()` currently. I think it would be good to add some basic logging in addition to adding the library. Just so that it's easy to follow the general steps from the output.

**Comment by amit1307** [comment]
Sure, thanks for the info. I should get back in 1-2 days with something.

**Comment by amit1307** [comment]
Hey, have raised the PR to add some logs. Please let me know if you have any feedback on the change.
