### ISSUE TITLE
Tests not being executed in naked-objects

### ISSUE THREAD

**Issue by charlesfinley** [iluwatar/java-design-patterns#1669]
Naked objects module has tests that are being skipped during the maven build. 

These tests fail when executed by IntelliJ. They also fail if you try to update to JUnit5 via junit-vintage-engine. 

> This issue partially resolves #1500

**Comment by charlesfinley** [comment]
To further clarify this issue - this module should be updated to JUnit 5 and the tests should be refactored as necessary.

**Comment by PakhomovAlexander** [comment]
Hi @charlesfinley ! Could I take this?

**Comment by charlesfinley** [comment]
> Hi @charlesfinley ! Could I take this?

Feel free. Remove any dependency on JUnit4 or junit-vintage-engine and have the tests pass.

**Comment by ohbus** [comment]
> Hi @charlesfinley ! Could I take this?

Go ahead!

**Comment by PakhomovAlexander** [comment]
Hi @charlesfinley @ohbus ! 

I've tried to migrate `naked-objects` module from junit 4 to junit 5. It went well for `dom` module. But it turned out that `integtests` module is deeply dependent on junit 4 rule API. It seems not possible to migrate without big changes. 

`naked-objects` pattern is a reference for apache isis. The current example is completely out of date. There is [simple-app](https://github.com/apache/isis-app-simpleapp) that uses junit 5. 

So, we can replace current `naked-objects` with `simple-app` example. Or just leave a reference to `simple-app` in order to have it always up to date.

**Comment by charlesfinley** [comment]
> Hi @charlesfinley @ohbus !
> 
> I've tried to migrate `naked-objects` module from junit 4 to junit 5. It went well for `dom` module. But it turned out that `integtests` module is deeply dependent on junit 4 rule API. It seems not possible to migrate without big changes.
> 
> `naked-objects` pattern is a reference for apache isis. The current example is completely out of date. There is [simple-app](https://github.com/apache/isis-app-simpleapp) that uses junit 5.
> 
> So, we can replace current `naked-objects` with `simple-app` example. Or just leave a reference to `simple-app` in order to have it always up to date.

If the pattern is obsolete I don't see an issue getting rid of it, but that's obviously up to @iluwatar and @ohbus.

**Comment by iluwatar** [comment]
I'm aware the naked objects example is pretty old and out of date already. I think the better route forward for us here would be to get the latest simple-app example from the Isis website and work to make it fit into our pattern catalog. I opened a new issue https://github.com/iluwatar/java-design-patterns/issues/1683 for this.
