### ISSUE TITLE
Sort the Array in the Descending order

### ISSUE THREAD

**Issue by priyanshu688** [iluwatar/java-design-patterns#1827]
Here the set of Array is given and You have to sort the array in the descending order. The Before and After sort element should also be printed.

**Comment by xujnan** [comment]
退订---- Replied Message ----FromPriyanshu ***@***.***>Date10/03/2021 02:03 ***@***.***> ***@***.***>Subject[iluwatar/java-design-patterns] Sort the Array in the Descending order (#1827)
Here the set of Array is given and You have to sort the array in the descending order. The Before and After sort element should also be printed.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iluwatar/java-design-patterns/issues/1827",
"url": "https://github.com/iluwatar/java-design-patterns/issues/1827",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ohbus** [comment]
@priyanshu688 How is this a relevant issue?

I would request you to please shed some light on this.

**Comment by priyanshu688** [comment]
@ohbus As if sort() takes the third parameter which specify the order. So It can be like which we can use to sort or whether another solution exists?

**Comment by iluwatar** [comment]
@priyanshu688 please provide a proper explanation of what needs to be done or this issue will be closed. Start by pointing out the pattern and the code unit you are talking about.

**Comment by ohbus** [comment]
I'm really sorry @priyanshu688 as this is not the right repository for doing what you are seeking.

I apologize @ShubhanshuJha @Arjun6112 as this is not available for taking. But you can always find something to work within our repository from [**here.**](https://github.com/iluwatar/java-design-patterns/issues?q=is%3Aopen+is%3Aissue+label%3A%22info%3A+help+wanted%22) Feel free to let us know by commenting which one would you like to work on. And be sure to go through our [Wiki.](https://github.com/iluwatar/java-design-patterns/wiki)

Thank you so much @iluwatar and @npathai for helping this out.
