### ISSUE TITLE
Fluent Interface pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#184]
http://www.martinfowler.com/bliki/FluentInterface.html

http://stackoverflow.com/questions/31733262/what-is-this-the-name-of-this-java-state-based-design-pattern

**Comment by hannespernpeintner** [comment]
I try to implement it :)

**Comment by hannespernpeintner** [comment]
Sent a pull request https://github.com/iluwatar/java-design-patterns/pull/207 :)

**Comment by npathai** [comment]
@hannespernpeintner Thanks for your PR. :+1: 
I have not read the whole example but just took a brief idea. @iluwatar Would like to hear your suggestion on "Should we implement this example as a `FluentIterable`". This will be a minimal mock of [Guava's FluentIterable](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/FluentIterable.html). I think it makes the pattern much easily understandable. 
It is just my opinion that using that example would be very close to how it will be used in real applications.
A mockup
```java
FluentIterable.from(integerList)
.filter(negatives())
.first(10)
.max();
```

@hannespernpeintner There are many more real applications one of them is Guava, Java 8 Stream API are some of them which we should document.

**Comment by npathai** [comment]
@iluwatar Or even better we can just use Java 8 Stream API to demonstrate it.

**Comment by hannespernpeintner** [comment]
You are welcome :) 
@npathai guavas fluentiterable is a complete and concise Implementation and could be a receipt by itself, i dont think one should reimplement it. However, maybe its source should be linked in the read.me?
Using the stream API would be easy and possible but isnt the key of this project to show how the pattern can be Used - and *implemented* as well?

**Comment by npathai** [comment]
@hannespernpeintner I agree with you. I think we should implement it by hand, a very minimal example. We are in the same dilemma as we faced with #93 . Whether we should implement it or just use existing library. There we have decided to use Camel for just showcasing the use of design pattern (because it would have required a lot of boilerplate framework classes to implement them). I was kinda in the inclined towards implementing them by hand. But after the discussion in #93 we decided to go against it.
Do you think we can come up with some better example?

**Comment by npathai** [comment]
@iluwatar Do you think we should have a discussion round about the example that we will be demonstrating prior to implementation. Reason is that I find it useful if the example demonstrated is nearer to a real application. But that can be just me.
Again it can mean that our tasks run longer because it can be difficult to come to a consensus. I don't know just thinking out loud. Guys?

**Comment by npathai** [comment]
Some interesting references:
 - [Ways to implement fluent interface](http://stackoverflow.com/a/17937946/1719067)

> Note that there are at least three ways a fluent interface can work: by having each member of an instance return a new instance with the appropriate change applied, by having each member mutate the instance upon which it is invoked and return that, or by having each member return an instance of a lightweight patch object which holds a link to either the thing being modified or the previous patch. The last style requires that some action be taken to apply all the patches, but if the object being modified is large and many changes are necessary, it can minimize the amount of copying that's required.

 - [Drawbacks of self-referential method chaining](http://programmers.stackexchange.com/questions/80244/are-there-any-actual-drawbacks-to-self-referential-method-chaining)
 - [Java fluent API designer crash course](http://blog.jooq.org/2012/01/05/the-java-fluent-api-designer-crash-course/)

**Comment by npathai** [comment]
[JOOQ](http://www.jooq.org/) should also be documented as application. It implements database query DSL which is most common use case of Fluent interface seen in almost all languages.

**Comment by hannespernpeintner** [comment]
From my point of view, the example should be as  clearly seperable as possible from state patterns. And most tutorials tend to kind of over-weight the formal DSL thing. So it might be best to implement a simple fluentiterable based on the guava Code. Real-world and simple. The most important part would then be the Implementation, because that's what people are interested in (how to use fluent Interfaces is intuitive).

I First thought domain-focused method chaining is the most important part of fluent interfaces, therefore i implemented a simple class structure that can easily ported. If anything else, i would go for the fluent iterable.

**Comment by npathai** [comment]
@hannespernpeintner I agree. A simple implementation of `FluentIterable` would be perfect for this. I had created a mockup of `FluentIterable` for personal learning. I'll be available for any help. We can utilize JDK8 interfaces `Function`, `Consumer`, `Supplier`.

**Comment by hannespernpeintner** [comment]
Okay so next try: I made a small implementation of the FluentInterface similar to Guava. Of ourse I didn't reimplement all the functionality. I used the all-Java-stuff like Iterator interface, Joiner, Function, Consumer etc.

When code and documentation are good, I'll do the readme stuff.

Thanks :)

**Comment by npathai** [comment]
Great I will review it.

**Comment by geniusgeek** [comment]
@iluwatar @npathai I revieved your implementation of the Fluent interface Pattern and i liked the way you implemented it using JDK8 interfaces Function, Consumer, Supplier please which resources did you  use to learn java 8?

**Comment by npathai** [comment]
@geniusgeek These all interfaces are new additions to java but existed in Google Guava since a long time. [Google Guava Functional Explained](https://code.google.com/p/guava-libraries/wiki/FunctionalExplained) can be a good starting point. Read a bit on Functional programming in Java for more. Keep one thing in mind that these constructs existed since long time but have got recent hype after Scala came out maybe. All these interfaces are Functional interfaces (single method interfaces) that have single responsibility. 

 - `Predicate` takes some input and returns `true` or `false`.
 - `Consumer` takes some input and does not return. Similar to `foreach()`, `foreach()` needed a way to pass the element to some behavior which can accept that input.
 - `Function` takes some input and returns some output. Similar to `map()`, it needed a function that can transform the input from one type to other.

It really comes to you naturally when you try some examples in Guava or Java 8. Its quite intuitive :smiley:

**Comment by geniusgeek** [comment]
thanks

**Comment by npathai** [comment]
@hannespernpeintner
Two points to make:
 - `FluentInterface` should not be called `Architectural` pattern. We can put it in `Other` category.
 -  Missing consequences section. I will take care of this.

@iluwatar I will close this issue once I complete work on both points above. Do you agree with point 1?

**Comment by iluwatar** [comment]
`Architectural` caught my eye as well. What you suggest is ok for me.

**Comment by npathai** [comment]
I changed the category and a few more changes
 - implementation strategies
 - added more real applications of different DSLs
 - a new reference

I have stayed away from discussing consequences for now as I didn't want to spread misinformation due to lack of much experience in this matter. This is something we can surely target in future for all patterns. 

So closing the issue.
