### ISSUE TITLE
Casting Issue 

### ISSUE THREAD

**Issue by MaheshMadushan** [iluwatar/java-design-patterns#1957]
![CB](https://user-images.githubusercontent.com/58337761/151684862-b05babb8-180e-472d-b6c0-923b0b16127a.png)

**Comment by iluwatar** [comment]
@MaheshMadushan can you explain what this issue is about?

**Comment by MaheshMadushan** [comment]
Hi @iluwatar , There is a small casting issue. 
![image](https://user-images.githubusercontent.com/58337761/153973583-cf198d38-4525-4a32-ae44-a45b5c6f4972.png)

**Comment by Yashwant-Tailor** [comment]
Hi @MaheshMadushan @iluwatar .
I'm beginner in java and during learning the java literals , I encountered one nice point which address this issue . 
In java **integer literal** can always be assigned to a **long** variable . However , to specify a **long literal** you will need to explicitly tell the compiler that the literal value is of type **long** . We can do this by appending an **uppercase** or **lowercase** **L** to the literal .
Here in this case we have variable **futureTime** as type of **long** type but the literal assigned to it is of type **integer** . So here compiler first do the casting of **1000 * 1000 * 1000 * 1000** to an integer literal and then assigned it to **futureTime** .
Solution to this problem is to use the **long literal** for example :

- **1000L * 1000 * 1000 * 1000**
- **1000 * 1000L * 1000 * 1000**
- **1000 * 1000 * 1000L * 1000**
- **1000 * 1000 * 1000 * 1000L**
These are few valid long literal we can use ( we can also use variation like 1000000000000L ) .
I hope you got my point here .

**Comment by rushisuper** [comment]
Hi is this issue still up for taking, or is it closed? I would like to contribute

**Comment by iluwatar** [comment]
Fixed with https://github.com/iluwatar/java-design-patterns/pull/1994
