### ISSUE TITLE
Ensure plugin compatibility with Java 17

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2033]
This issue is a part of the Java 17 transition plan at https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition.

The Maven build uses a plethora of plugins. In this issue let's ensure that all the used plugins have been updated to versions that support Java 17.

Acceptance criteria

- All the Maven plugins have been updated to recent versions that support Java 17

**Comment by HeVictor** [comment]
Hi, I would like to give this a crack if that's alright. Thanks!

**Comment by HeVictor** [comment]
Hi @iluwatar, I've been working on this issue and if it's alright I'd like to ask for some tips just to see if I'm on the right track. So far after forking and cloning the repo locally I've built the project in my IDE and I've configured it to use Java 17. Initially my approach was to go through each plugin to see if their versions have any release notes on whether it supports JDK 17 and then bump relevant ones in the POM file, but while some plugins mention this from their release notes I couldn't find this info for a lot of them anywhere (although sometimes I can find a couple of issue threads on other repos talking about fixing JDK compatibility issues for a plugin by bumping it above a certain version). 

Thus currently my approach is running `mvn clean install` to see what errors pop up from each of the design pattern directories and see if I can fix them through upping the plugin versions. My question is since there will be other incompatibility issues the project faces after switching to Java 17 as-is (such as due to library dependency incompatibilities), how should I make the changes in my PR to ensure plugin compatibility is met even if there's still errors during build or install? In other words what kind of testing steps should I take to verify that I've ensured compatibility for all the plugins in the project, beyond building the project in maven and running the unit tests?

I'm happy to put up a draft PR to show the changes I've made so far if it's easier to discuss where I'm at. Thanks so much for your time.

**Comment by iluwatar** [comment]
I think executing `./mvnw clean install` should uncover 99% of the issues. Additionally, we can try to run each pattern using the command line e.g. `java -jar proxy.jar`, but the unit tests should mostly cover it already.

**Comment by yonatankarp** [comment]
@HeVictor can we close this issue? or are there any other dependencies that should be migrated first?

**Comment by HeVictor** [comment]
@yonatankarp As far as I know all of the other plugin dependencies work under Java 17 except for the current `naked-objects` pattern directory which will break, as I mentioned in the previous comment. I'm still having a crack at updating the naked objects module to the latest version using `Apache Isis` (#1683) which will solve this problem when that is completed, however it is going a little slow at the moment.

@iluwatar Hope it's alright if I pull you into this discussion. Do you think it could be good to close this issue and keep the problem of updating `naked-objects` within #1683 or should this still remain open until that's resolved?

**Comment by iluwatar** [comment]
@HeVictor thanks for the update. I think we can close this issue as completed.

**Comment by iluwatar** [comment]
Besides the naked objects pattern, we need to complete #2035 #2036 #2037 before switching to Java 17 build. See https://github.com/iluwatar/java-design-patterns/wiki/19.-Java-17-transition
