### ISSUE TITLE
Better Structure / More Info

### ISSUE THREAD

**Issue by noobxgockel** [iluwatar/java-design-patterns#205]
Hello there,

so i recently got the "Head First Design Patterns" book from my boss and i found a pretty nice Structure to put patterns into it. Maybe we could adapt to something like this. I mean the overview you get from this collection of patterns is really nice and helpfull but i find if i wanted to use some pattern mentioned here i havent got enough information to fully comprehend and implement the patterns correctly so i go to other pages like wikipedia or sorts.

The Structure the book mentions:
- Name + Classification/Category
- Intent / Pattern definition
- Motivation (Describes concrete scenarios, their problems and how this pattern solves the problems)
- Applicability (Situations in which the pattern can be applied)
- Structure (Diagram)
- Participants (Describes the classes and their respective roles in the pattern)
- Collaborations (How the participants work together)
- Consequences (The Effects this pattern has, good and bad)
- Implementation/Sample Code (Techniques, thought process, ...)
- Known Uses
- Related Patterns

This resource covers quite a lot of the mentioned points, but not all of it and not in a very detailed manner. So maybe this issue is something we could work towards, maybe not in the near future, but when we find time for it. But i believe making this happen will move us one step closer to beeing the best resource for java design patterns C:

Hope you like it ^^

**Comment by npathai** [comment]
@noobxgockel Yes that surely will help. Because one thing is to understand the patterns, it is way different to understand where and how to implement them. As they never are implemented as island, they actually are in subtle ways linked and used with each other. That's [Pattern Language](https://en.wikipedia.org/wiki/Pattern_language) a term coined by Christopher Alexander for building architecture.
There can be another analogy of ingredients and recipe. Ingredients - individual patterns and the Recipe is pattern language (actual real life architecture).

What GoF book and POSA series tries to achieve with all these sections is to give enough information so that a language can be formed by using vocabulary of these individual patterns. So yes we should strive to provide as much information with a pattern as possible at least with new patterns we implement. I hope @iluwatar agrees with this.

What we also need to promote and document is, thinking of design patterns as a form of communication, and not over engineering the design by unnecessarily shoving in various design patterns just because we can. Many starters do this. Just remembering the YAGNI principle.

Any comments? @noobxgockel @iluwatar

**Comment by iluwatar** [comment]
This is good to discuss. I think this has all to do with our vision and what we want to achieve with this project.

Personally I started this repository to learn myself how to implement the patterns. I started with the bare minimum what I need. I found most valuable the intent (what does it do) and applicability (when to use) and simple class diagram showing the relationships. I think this is the "core" of the documentation. 

However, I find the essence of the project is the pattern code examples. I think we don't want to be a book. We don't want to compete with all the pattern books but rather complement them with real working examples that anyone can compile, tweak and run. This is what all the books are missing and where we can shine. We should keep it our first priority to make the code examples as good as possible.

Then again, I understand @noobxgockel 's concern to make the documentation shine since he is working on the web site where the code is not visible. And I want the web site to be exemplary good  also.

**Comment by iluwatar** [comment]
If I have understood correctly the repository's front page is not going to display the pattern documentation anymore but rather link to the web site. @noobxgockel can you elaborate what is your vision on this?

**Comment by noobxgockel** [comment]
As to the repo front page links: yep that would be one possibility, but only going through the website is also an option.

My Vision... I just thought that such a structure is more inviting and maybe for some of us more informative than what we currently have.

And @iluwatar , if you want it to be code heavy, then i have no problem with that at all. There still is the posibility to add dynamic links from the website to the code, or even embed it into the index.md or the website itself (e.g. gist-it.appspot.com)

I hope you understand what i mean (im not native english, sometimes its hard to convey a point for me)

**Comment by iluwatar** [comment]
This sounds fine to me. Go ahead and proceed with the vision you have. We can leave the links out of the `README.md` and go through the web site only.

@noobxgockel I had some questions about the new system. Specifically how do we add new patterns with the new system. This in Gitter, let's discuss there.

**Comment by npathai** [comment]
@iluwatar Fair enough. I understand we should not go overboard with documenting each thing the book already documents, just the most important bits. But I think the _bad_ are the most important part of it. No pattern is just all good.

**Comment by iluwatar** [comment]
Yes, I don't mean to leave everything out - just the less important parts. Which ones do you think are the most important? So far we have

- name / classification
- intent
- applicability
- diagram
- known uses (real world examples)
- implementation / sample code

Maybe add these

- consequences (the good and the bad)

Thinking of leaving out

- motivation
- participants
- collaborations
- related patterns

**Comment by npathai** [comment]
For now I think we should just add _consequences_.

**Comment by iluwatar** [comment]
Agreed then. Our current pattern template is:

- name / classification
- intent
- applicability
- diagram
- known uses (real world examples)
- implementation / sample code
- consequences (the good and the bad)
