### ISSUE TITLE
Web site links not working

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#209]
- the toolbar links give 404 when clicked
- the pattern links do nothing when clicked (what should they do?)
- can we remove the bottom most line with email and rss links?

**Comment by noobxgockel** [comment]
> * the toolbar links give 404 when clicked
> * can we remove the bottom most line with email and rss links?

should be fixed now

> * the pattern links do nothing when clicked (what should they do?)

yes currently the links on the "Home" page dont do anything, thats because the readme doesnt contain all the patterns anymore...

I left all the lists in there until we have migrated to the category and tag system of the website, but after that i think the links or even the list should be removed from the main README. I'd suggest the main readme to only be general information about the project, faq, how to contrib, license, credits etc...  but nothing directly related to individual patterns. Because for that we would have the website now ?

What do you think of that ?

**Comment by iluwatar** [comment]
Fair enough. I think we try it as you suggested. Will you make the changes for the `README.md`?

**Comment by noobxgockel** [comment]
Yes i could do that. I'll make another issue for fixing all those categories and tags.

**Comment by noobxgockel** [comment]
I'll close this for now and edit #213 to include the point of removing the patternlist from the readme after we finished categorizing and tagging all patterns.
