### ISSUE TITLE
Repository vs DAO

### ISSUE THREAD

**Issue by stephen-lazarionok** [iluwatar/java-design-patterns#216]
I think that Repository pattern is not implemented in the correct way and it looks like DAO. Here is a good article about this http://thinkinginobjects.com/2012/08/26/dont-use-dao-use-repository/

**Comment by iluwatar** [comment]
Hi @stephen-lazarionok and thanks for pointing out the interesting article. We would like to improve the example so that it would better distinguish Repository from DAO. I noticed that the class naming could be improved and maybe add a query method that takes criteria as a parameter like they have in the article. Can you pinpoint more improvements we should apply? PRs are welcome too, if you would rather work that way.

**Comment by stephen-lazarionok** [comment]
I can work on Repository pattern and improve it. The only thing that I do not have enough time as I took some patterns to implement and in addition to that I have real projects I've been working on. So it may take some weeks to implement all the stuff on me :) If it is okay then I will go ahead.

I did not review all the code I just took a look at the repository pattern implementation to find out what is a default DB is used and saw that issue :) That is why I raised it. Once I get some spare time I will check out the rest of the codebase.

**Comment by shaileshkhose** [comment]
I can work upon the udpates required for correcting the Repository pattern, as desired by @stephen-lazarionok. Let me know if that would be okay.

**Comment by npathai** [comment]
@shaileshkhose Sure go ahead. Your contribution is welcome.

**Comment by hoswey** [comment]
The Repository Pattern so awesome than the Dao Pattern, and this issue has nothing progress since Aug. 
I want to work on this issue, let me know if that would be okay.

**Comment by iluwatar** [comment]
Great @hoswey go ahead!
