### ISSUE TITLE
Security vulnerability in H2 database

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2297]
The currently used H2 database version 1.4.190 has multiple security vulnerabilities. To mention a few:

1. - H2 Console before 2.1.210 allows remote attackers to execute arbitrary code via a jdbc:h2:mem JDBC URL containing the IGNORE_UNKNOWN_SETTINGS=TRUE;FORBID_CREATION=FALSE;INIT=RUNSCRIPT substring, a different vulnerability than https://github.com/advisories/GHSA-h376-j262-vhq6
2. - H2 Console in versions since 1.1.100 (2008-10-14) to 2.0.204 (2021-12-21) inclusive allows loading of custom classes from remote servers through JNDI.
3. - The package com.h2database:h2 from 0 and before 2.0.202 are vulnerable to XML External Entity (XXE) Injection via the org.h2.jdbc.JdbcSQLXML class object, when it receives parsed string data from org.h2.jdbc.JdbcResultSet.getSQLXML() method. If it executes the getSource() method when the parameter is DOMSource.class it will trigger the vulnerability.

Acceptance criteria

- H2 database has been upgraded to the latest version

**Comment by bhati00** [comment]
@iluwatar , is solution is to update the version of H2 database or something else .
Above issue is also mentioned here officially in H2 database repo [issue](https://github.com/h2database/h2database/issues/3195).

**Comment by iluwatar** [comment]
Yes, update the version (see the acceptance criteria). Would you like to try it @bhati00 ?

**Comment by bhati00** [comment]
yes sure @iluwatar , i would like to try.

**Comment by bhati00** [comment]
Sir , where i can find the details about this project , how is it developed and its architecture .
 Why we use the H2 database, is it only for the testing purpose . ?

**Comment by bhati00** [comment]
Sir, i did updated the version of H2 database by changing the version of H2
in pom.xml . But it failed the test case.

**Comment by iluwatar** [comment]
After changing the H2 version, you need to fix everything so that the CI build works again @bhati00 That's the difficulty in this task.

**Comment by bhati00** [comment]
Sir , can you please specify a bit that, what kind of changes should i made to in order to fix everything .I've read this article for  [migrate to hibernate 2.0](https://www.h2database.com/html/migration-to-v2.html#:~:text=your%20own%20risk.-,Upgrading,of%20this%20command%20for%20details.) , and one another thing , where we did specify the details about the h2 database , in rest api we use application.properties.

**Comment by bhati00** [comment]
Hello Sir, Can you please specify a bit , what kind of changes should i made to in order to fix everything . I've read this article for [migration to hibernate 2.0](https://www.h2database.com/html/migration-to-v2.html#:~:text=your%20own%20risk.-,Upgrading,of%20this%20command%20for%20details.), and one another thing sir, Where did we specify the details about the h2 database , like in spring-boot we use application-properties.

**Comment by iluwatar** [comment]
Hmm I didn't get any errors after the upgrade. Could you just create the pull request with the updated dependency and we can check if it's just your workstation?

**Comment by bhati00** [comment]
@iluwatar , i've made the [pull request ](https://github.com/iluwatar/java-design-patterns/pull/2298), it solves two issues , since previous one was'nt merged that's why i've commited to same branch. 
I'm not getting error in my workstation Sir, its circle.ci which shows the error , **maven build failed** .

**Comment by robertvolkmann** [comment]
I previous tried to upgrade the H2 database but failed with some strange error message that need non-trivial investigation.

**Comment by bhati00** [comment]
@robertvolkmann , did you just simply added the dependency or also made some another changes for upgrading the database.

**Comment by robertvolkmann** [comment]
I simply pumped the version and it failed. Therefore I expect some additional changes.

**Comment by bhati00** [comment]
wow , great @robertvolkmann , you've solved the issue .
i was seacrching in the project , where did the database created , @robertvolkmann  , why did we created it in domain-modal . And why did you  droped the table according to their dependency .

**Comment by robertvolkmann** [comment]
@bhati00, the H2 database is automatically created if absent.
You have to drop the tables according to their dependency. In our case, we cannot drop the table CUSTOMERS before PURCHASES because the latter still has a reference to CUSTOMERS.
