### ISSUE TITLE
Java 17: Update switch expressions

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#2376]
Java's switch expression syntax has vastly evolved over the years. It's well described at https://medium.com/@javatechie/the-evolution-of-switch-statement-from-java-7-to-java-17-4b5eee8d29b7

Acceptance criteria

- Java 17 switch expressions have been applied throughout the repository

**Comment by AlexMitDemBart** [comment]
Hello @iluwatar,

I haven't contributed to open source yet. But I want to start now.

I am:
- Oracle Certified Professional Java SE 11 Developer
- Oracle Certified Professional Java SE 17 Developer

I could take this Issue and refactor all switch expressions to the new syntax.

**Comment by AlexMitDemBart** [comment]
Hello @iluwatar thank you for assigne me to the issue.

when i checkout fresh master branch and run mvn checkstyle:check then multiple errors occure.
![image](https://user-images.githubusercontent.com/70911193/207944912-59bac98b-98bb-4c21-8bd1-7979ec7080a4.png)

I already have made all necressary changes to the switch statements and have and opened an pull request in draft. The Pull Request shows "all checks have failed" because of the checkstyle errors from master. 

I would be grateful if you could tell me how I should proceed here.

**Comment by iluwatar** [comment]
@AlexMitDemBart that command is not taking into account the checkstyle configuration we have in the pom.xml. Try `./mvnw validate` instead.

**Comment by mDyingStar** [comment]
@iluwatar 

Could it be, that the PAT (Personal Access Token) has expired?

![image](https://user-images.githubusercontent.com/70911193/208242273-8e6079e2-a508-4bfa-a21e-aef51e3562ca.png)

**Comment by akshatarora0013** [comment]
Hey @iluwatar can I work on this issue, I am new to open source but I have a good grip in Java

**Comment by akshatarora0013** [comment]
Made the pull request (issue #2376), changed all the switch expressions according to JAVA 17.

**Comment by jaswanthg76** [comment]
'm new to open-sourcing and I have no clue about what I should be doing. Can anyone guide me? I have basic knowledge of java
let me know in which way I can help you.
