### ISSUE TITLE
Microservices architectural pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#296]
The example should demonstrate the basic cases how to compose microservices together as described here: http://blog.arungupta.me/microservice-design-patterns/

**Comment by protopapa** [comment]
Hi,

I'm Anastasia . I would like to work on this issue of it is OK. 
Waiting to hear back.

Thanks and Cheers.

**Comment by iluwatar** [comment]
Hi there! You're welcome to work on it. I'll update the issue labels.

**Comment by protopapa** [comment]
Thanks!!!

**Comment by npathai** [comment]
@iluwatar Don't we need splitting of tasks here? Link explains 4-5 different patterns. Are all going to be implemented as one PR?

**Comment by neonds** [comment]
Hi! Maybe I can help in someway.

**Comment by iluwatar** [comment]
@npathai @protopapa as I see it this is a single architectural pattern and there are different flavours to it. In my opinion this issue could implement the basic case and explain the others.

I agree this is a big pattern to implement and would prefer to discuss the best way to implement it before we dig too deep into it.

**Comment by protopapa** [comment]
@iluwatar @npathai As I see it is for sure one pattern with 3 variations. For the last two listings I would like to research and study it a bit more before forming an opinion.

**Comment by neonds** [comment]
I agree with Idea to use the most simplest architecture. I was in a project where we use Repository and Service patterns, with Spring restfull and spring security with Jason Web Tokens (jwt) using DTO pojos . I think that is a good idea use a real example with a complete stack of layers.

**Comment by protopapa** [comment]
Hello! 
I believe that the simplest way to implement this pattern is, as it described on the Aggregator Microservices pattern. I also believe that the Proxy Pattern , Chained Microservices Pattern and Branch Microservices Pattern is a variation of the Aggregator. The Shared Data Microservices Patter and the Asynchronoys Pattern solve a different problem and if implement should be in a different task. 
I am waiting for your feedback. Cheers !

**Comment by iluwatar** [comment]
Hi @protopapa I think you have the right interpretation. For an example, you can look at the excellent [API Gateway pattern](https://github.com/iluwatar/java-design-patterns/tree/master/api-gateway) from @TylerMcConville

**Comment by protopapa** [comment]
Hello again @iluwatar  and @npathai ,
I looked at the API Gateway pattern, and at first look I thought that it is a variation of the aggregator pattern or the other way around. I made a small search to try to understand the differences and I think that as the Aggregator Microservices is described in this article is no different from the API-gateway. I also had a look at the below articles : [first link](https://dzone.com/articles/building-microservices-using)  and  [second link](http://microservices.io/patterns/microservices.html). 
My thoughts are: 
1. On both patterns all services are exposed through REST, so its not that the communication channel changes to make a difference. 
2. Also as it is stated at the article of Arun Gupta at the  aggregator component we can have business logic upon the data that is collected from the other services and expose them also through REST. 
Those are my basic thoughts, since perhaps I lack some experience I would like your thoughts and feedback.

**Comment by iluwatar** [comment]
Hi @protopapa I think you are right in the sense that technically API Gateway and Aggregator may look the same. The purpose of the patterns however varies. API Gateway provides different functionality for different devices whereas Aggregator provides unified API.

**Comment by protopapa** [comment]
Hey! I was a bit busy these days! I will keep working again! @iluwatar thanks for your answer.
