### ISSUE TITLE
Monad pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#335]
It is described in this talk: https://youtu.be/-k2X7guaArU

**Comment by npathai** [comment]
One more useful link: https://channel9.msdn.com/Shows/Going+Deep/Brian-Beckman-Dont-fear-the-Monads

A rather detailed discussion explaining the fundamentals of monads.

**Comment by Crossy147** [comment]
I will work on that issue tomorrow

**Comment by iluwatar** [comment]
Ok @Crossy147 I will update the issue tags.

**Comment by Crossy147** [comment]
I have one more questions, if i may.
I'm finishing my work with
https://github.com/iluwatar/java-design-patterns/issues/333 issue, the
monad pattern. I just need to deal with uml in eclipse, and code style
violation (in this commit
<https://github.com/Crossy147/java-design-patterns/commit/10bbf988ead88e92ab00223631313ffa58337c53>
IntelliJ changed code-style of another pattern to Google Java Style
<https://google.github.io/styleguide/javaguide.html> as you requested, but
it brokes the checkstyle violations somehow  :(. So a questions is in my
mind:
- Should I commit those changes labeled with #333 and pull request after
that (pull request before working with #335)?
- My code is rather similiar to the one presented on the movie on yt by
devoxx, it uses functional interface just as it is, and i really can't find
any better way to deal with this problem, than to adapt it to our cases to
present it as simple and clean as I can. Is it acceptable or do I need to
write it differently due to copyrights or sth?

2016-02-15 19:28 GMT+01:00 Ilkka Seppälä <notifications@github.com>:

> Ok @Crossy147 <https://github.com/Crossy147> I will update the issue tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iluwatar/java-design-patterns/issues/335#issuecomment-184336467>
> .
>



-- 

*GreetingsKamil Pietruszka*
