### ISSUE TITLE
Binding Properties pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#468]
https://en.wikipedia.org/wiki/Binding_properties_pattern
http://c2.com/cgi/wiki?BindingProperties

**Comment by Crossy147** [comment]
Hi @iluwatar, I can take this one.

**Comment by iluwatar** [comment]
Ok @Crossy147 it's yours.

**Comment by Crossy147** [comment]
@iluwatar can you please take a look whether this is what you meant for? 
Since BiDirectional property binding requires too simple approach (properties must be equal) or too difficult approach(the converting function needs to be a checked bijection) - but this one is tricky and I don't think that it should be included here.
 I've decided to show a bit more complex but still simple one direction property binding, that allows a chained binding (unfortunately on the same cathegory since java's wildcards  are limited and you cannot simply express that wilidcards in conversion function and target property stands for the same type :( ).

Can You please tell me whether i'm going in the right direction? Or should I rather show bidirectional binding only? Thanks in advance :)

**Comment by umarov001** [comment]
STFU STOP SPAM PLS

2017-03-08 22:13 GMT+03:00 Kamil Pietruszka <notifications@github.com>:

**Comment by iluwatar** [comment]
@Crossy147 is there a pull request for this? I can offer insight if you show me the code.

**Comment by Crossy147** [comment]
Nope, I've decided to wait for your approval with PR #546 first. :)

**Comment by iluwatar** [comment]
@Crossy147  are you still implementing this?

**Comment by iluwatar** [comment]
This task is free

**Comment by tiennm99** [comment]
Could I take this one @iluwatar?

**Comment by tiennm99** [comment]
Sorry but I can not help you with this issue anymore. New rules with CheckStyle blocks me. I'm not professional enough to write code with that quality. Hope you find some better one can help you with this.

**Comment by iluwatar** [comment]
Duplicate of #67
