### ISSUE TITLE
The link to principles needs to be updated

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#479]
The `README.md` text "Programming/Software Design Principles" should link to content on the same web site e.g. http://java-design-patterns.com/principles/

Note that the link needs work on http://iluwatar.github.io/java-design-patterns/ web site too.

**Comment by markusmo3** [comment]
Hmm, we have a few options here:
* sacrifice the github link (use jekyll or do a relative link to "principles/" which points to nothing on github.
* sacrifice the website by hardlinking to java-design-patterns.com/principles/
* remove link completely

**Comment by iluwatar** [comment]
Linking to a page on the same site is such a basic functionality that I feel we must develop a real solution for this other than a workaround.

**Comment by markusmo3** [comment]
those are all real solutions, everything else will be a workaround (hacking with js or jekyll).
The Problem stems from the cross-compatibility between github and the website.

I'd prefer the last to be honest. "remove link completely" because i dont think we need to link to a page that is displayed in the navbar of our website.
