### ISSUE TITLE
Object Mother pattern

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#498]
http://martinfowler.com/bliki/ObjectMother.html

**Comment by igeligel** [comment]
Hi! Great library :+1: 
I want to take this one but what is the main difference to a simple [factory pattern](https://www.tutorialspoint.com/design_pattern/factory_pattern.htm)?

Since the link you shared was working with employees i have thought for something like this:

```java
EmployeeMother mother = new EmployeeMother();
Employee heather = mother.bear(EmployeeName.HEATHER);
Employee heather = mother.bear(EmployeeName.JOHN);
```

where EmployeeName is an enumeration of names. Is this the right approach?

**Comment by iluwatar** [comment]
@igeligel some elaboration here http://stackoverflow.com/questions/923319/what-is-an-objectmother. I'll change to labels to indicate you're working on it.

**Comment by igeligel** [comment]
Yeah i want to work on this. I will probably code it the next days and check for a code review here then (i will announce if i think it is ready).

**Comment by igeligel** [comment]
I have made the first try. The only thing that has not worked yet is the PlantUML diagram. I will try to make this tomorrow and commit to the fork again. A code review would be appreciated :)

**Comment by iluwatar** [comment]
Don't worry about the PlantUML diagram - it is still experimental and we don't check it when you make the pull request. ObjectAid diagram is the one you should generate, as per instructions here https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute
