### ISSUE TITLE
Remove HTML-Proofer from build

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#522]
There's a module called HTML-Proofer doing link analysis each time gh-pages branch is built. Lately it has been failing for various reasons (e.g. https://travis-ci.org/iluwatar/java-design-patterns/builds/177235379) and I would suggest that it would be removed from the build altogether.

**Comment by markusmo3** [comment]
Heya there,

im against this change, but also sorry i didnt pay a lot attention to those build failures earlier.

The HTML-Proofer uncovers important problems, like absolute links in [the newest blog page](https://raw.githubusercontent.com/iluwatar/java-design-patterns/gh-pages/_posts/2016-11-03-build-maintainable-systems-with-hexagonal-architecture.md):
```
![Hexagonal Architecture]({{ site.url }}{{ site.baseurl }}/assets/hexagonal-architecture.png)
```
This will fail, on purpose and in my opinion for good, because every build of the website would depend on our main webpage jdp.com instead of on itself. Absolute links for linking inside our own website arent good. using `site.baseurl` is enough in this case.

And the sonarqube issue seems to be an issue with certificates and/or ssl connection. Im working on that.

**Comment by iluwatar** [comment]
Ok, we can keep it if you insist but then we have to fix the current issues and react quickly when it reports errors. Also, I have modified the build sequence in https://github.com/iluwatar/java-design-patterns/commit/de7abf9e6e9c73157ef3a4e22c25d842e937eea7 to run the S3 deployment despite of HTML-Proofer errors. I don't know if this should be reverted.

**Comment by markusmo3** [comment]
The newest build is successful again:
https://travis-ci.org/iluwatar/java-design-patterns/builds/177775274

And im fine with the s3 deployment going through even if the HTML-Proofer fails. It's just a tool for reinforcing good valid websites, but if rapid prototyping is needed it can be a hassle. This will most likely hide some issues like those internal links but thats okay, i guess ^^

**Comment by iluwatar** [comment]
Good enough for me. Thanks for fixing this @markusmo3 :+1:
