### ISSUE TITLE
Page-Object source placement?

### ISSUE THREAD

**Issue by markusmo3** [iluwatar/java-design-patterns#524]
The Page-Object patterns source code is mainly place in src/test instead of src/main, where only the App class lies.

Im really not familiar with the pattern and the implementation, but the issue is that the uml-reverse-mapper only adds src/main classes to its diagram. Due to them missing [the puml file is basically emtpy](https://github.com/iluwatar/java-design-patterns/blob/master/page-object/etc/page-object.urm.puml)

Would it be possible to move the source or would that break the pattern/test contract? ([The eclipse-generated diagram](https://github.com/iluwatar/java-design-patterns/blob/master/page-object/etc/page-object.png) shows the 3 pages)

**Comment by iluwatar** [comment]
I see the problem. However, this is a testing pattern and think that the source code layout was intended to be like this. Maybe @colinbut has a comment on this?

**Comment by colinbut** [comment]
The Page-Object patterns source code is mainly placed in src/test because it is predominately a test pattern as mentioned. 

I'm not that really familiar with the usages of the puml file but my personal opinion is that i don't advise moving the source just to solve this uml-reverse-mapper issue as that would break the pattern intention/contract. The page objects are only used by test classes and doesn't make sense to live with the application code under test. Thus they should ideally be close to the test classes as possible.

My proposed solution would be:
to go back to a multi-module project structure (which was how i initially implemented this in my first draft of this pattern implementation).

So we would have 2 sub modules:
1 module is a project that represents the sample application under test. 
The other module is the test project which tests that sample application. This means it has its own project structure allowing the page objects to live under the `src/main` folder with the tests that uses them which are placed under `src/test` as usual. 

The benefit of doing this is:

1. It keeps the pattern contract intact, and perhaps demonstrates a more realistic usage of structuring projects that uses this pattern. 
2. As the page objects now under the src folder of the sub module project then i believe this should allow the `uml-reverse-mapper` to work.

thanks.

**Comment by iluwatar** [comment]
@colinbut this restructuring sounds good to me since it enables uml-reverse-mapper to do its job. Would you be able to create a pull request for this?

**Comment by staillebois** [comment]
I implemented the proposed solution by @colinbut and I created 2 sub-modules. @iluwatar I create a pull request for this.
