### ISSUE TITLE
Adapter pattern in Arrays.asList

### ISSUE THREAD

**Issue by CoXier** [iluwatar/java-design-patterns#628]
First of all thank you for this awesome repo. In `adapter` pattern section, you mention `Arrays.asList` does like this.

```java
    public static <T> List<T> asList(T... a) {
        return new ArrayList<>(a);
    }
```
So `List` is expected by the client?

```java
 private static class ArrayList<E> extends AbstractList<E>
        implements RandomAccess, java.io.Serializable
    {
        private static final long serialVersionUID = -2764017481108945198L;
        private final E[] a;

        ArrayList(E[] array) {
            a = Objects.requireNonNull(array);
        }
      .....
}
```
So `E[] a` is adaptee in the pattern? Am I right?

**Comment by dosdebug** [comment]
@CoXier Term `Adaptee` in this particular scenario means, something which needs an adaptation or say modification. `Target` is the type to be adapted or modified to. So, `asList` method is using the adapter pattern to modify `Adaptee` i.e. `T... a` to `Target` as `List<T>` .

`E[] a` is not an `Adaptee` in this scenario as per my understanding since `ArrayList` is not an Adapter but `asList` method is an adapter.

**Note:** Everything I said above is only my opinion and might differ from the actual author of the pattern `Adapter` or JDK developers.
