### ISSUE TITLE
Messaging (EIP)

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#72]
https://en.wikipedia.org/wiki/Messaging_pattern

**Comment by adiaholic** [comment]
i've read about different Messaging designs,
what am i supposed to do next to contribute ?

**Comment by codinghog** [comment]
Start by reading https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

@adiaholic If you want to contribute to EIP, let me know. I covered some of the EIP here so I can help you.

@iluwatar This issue is marked as (EIP) but EIP Messaging Patterns in general contain different patterns covered by other issues here. See: http://www.enterpriseintegrationpatterns.com/patterns/messaging/ Maybe this issue should be closed?

**Comment by iluwatar** [comment]
Ok, closing as duplicate
