### ISSUE TITLE
Utility class

### ISSUE THREAD

**Issue by javatlacati** [iluwatar/java-design-patterns#746]
I've seen something called "Utility class" to hold only utility functions, their design is similar to [class for constants](http://www.javapractices.com/topic/TopicAction.do?Id=2).

You can find a good example in lombok: https://projectlombok.org/features/experimental/UtilityClass

is that considered a design pattern?

**Comment by iluwatar** [comment]
I would not consider it as a design pattern. It is more like convention to separate common code. It should be noted that there are downsides with utility classes. They are not object oriented but procedural code, and depending on static functions creates hardwired dependencies which makes code hard to test.

**Comment by ryantheleach** [comment]
I've seen a unit testable version, where the utility class contains 0 state, has an interface for unit tests, but otherwise is comprised only of what could be static functions, if not for the instance needed to be able to mock the data.

I'd say that this (create a really thin interface, around an otherwise static object) could make for a decent pattern, even if it's considered somewhat of an anti-pattern compared to including the functionality on the class that matters... But each to their own coding styles. In some cases it makes a ton of sense.

**Comment by iluwatar** [comment]
Thanks @ryantheleach those are good arguments. If someone wants to try implementing this we can consider adding it to the catalog.

> I disagree that utility classes should have a constructor that throws, you can always make the constructor private if you truly never want it to be called right?

I guess one could invoke the private constructor anyway using reflection.

**Comment by npathai** [comment]
@iluwatar I agree with you, I would not consider this a pattern as well.
