### ISSUE TITLE
Maven build fail - Project "image-microservice" pom.xml lack of version field

### ISSUE THREAD

**Issue by zhangyuejia** [iluwatar/java-design-patterns#834]
Hi. When I run "mvn eclipse:eclipse" in the base path to convert to eclipse project.
An error occur and it's error info as below.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse (default-cli) on project image-microservice: Execution default-cli of goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse failed: For artifact {org.springframework.boot:spring-boot-dependencies:null:jar}: The version cannot be empty. -> [Help 1]  `

Does the 'version' field is abscent? 
The target dependency in java-design-patterns\api-gateway\image-microservice\pom.xml is:

## <dependencies>
       <dependency>
         <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
       </dependency>

**Comment by neerajmahajan** [comment]
Hi,

This error is coming, because 'spring-boot-dependencies' dependency is redeclared inside dependencyManagement section of image-microservice project without specifying it's version.  This dependency has already a version in the top parent pom.xml (https://github.com/iluwatar/java-design-patterns/blob/master/pom.xml).

To correct this issue remove dependencyManagement section from  java-design-patterns\api-gateway\image-microservice\pom.xml and declare this dependency in dependencies section of this pom.xml.

Kind Regards,
Neeraj Mahajan

**Comment by snehalatapandit** [comment]
Hi,
Maven build is still failing.
I have found below modules in which the spring-boot-dependencies are redeclared in the 'dependencyManagement' section due to which the mavel build fails :
1. 'aggregator-microservices\aggregator-service\pom.xml'
2. 'aggregator-microservices\information-microservice\pom.xml'
3. 'aggregator-microservices\inventory-microservice\pom.xml'
4. 'api-gateway\image-microservice\pom.xml'
5. 'api-gateway\api-gateway-service\pom.xml'
6. 'api-gateway\price-microservice\pom.xml'
The build succeeds if the redeclaration is removed. Should these dependencies be removed.

**Comment by perwramdemark** [comment]
I can fix this one!

**Comment by iluwatar** [comment]
Ok @perwramdemark
