### ISSUE TITLE
CI build is failing

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#903]
![image](https://user-images.githubusercontent.com/582346/61822672-d0864800-ae62-11e9-9572-148ee10f8b26.png)

**Comment by ptrax** [comment]
I think this is because you're using Travis CI's Xenial build environment, which seems to not allow you to install anything less than java 9 now. The choices are; upgrade to jdk 9+ or use the Trusty build environment. 

I went ahead and made a PR with the fix (using Trusty build environment). Build passes.
https://github.com/iluwatar/java-design-patterns/pull/911
