### ISSUE TITLE
Factory Method Pattern

### ISSUE THREAD

**Issue by neerajmahajan** [iluwatar/java-design-patterns#94]
There is an example given in the factory method pattern description which is Calendar.getInstance(), but I believe this is incorrect example because factory method defers the object creation to its subclass but getInstance() method of Calendar class is a static method and does not support overridden behaviour by its subclass.

Another thing I am not sure which is given in the factory method code is whether it is right to have  factory methods as public or it should be protected. My understanding of factory method applicability is the creator class can't anticipate the class of objects it must create but those object are part of that creator class and have aggregation relationship. I am not sure whether factory method also create and return those objects to the outside world using the public interface instead or protected. If we are making the interface public then I believe it is abstract factory pattern and not factory method pattern.

Please advice on my comments.

**Comment by iluwatar** [comment]
Hi @neerajmahajan and thanks for your comments. I believe you are right that `Calendar#getInstance` is not really a factory method for the reasons you explained. I will remove it from the real world examples.

**Comment by iluwatar** [comment]
For the second part of your comment I slightly disagree. Although the example is not strictly by the book (Design Patterns) I believe it demonstrates the essence of the pattern quite well: 

"Define an interface for creating an object, but let subclasses decide which class to instantiate. Factory Method lets a class defer instantiation to subclasses."

I do not think that it matters whether the factory method is public or protected or if the created instance is member of the creator class or not - these are just the implementation details that may vary.

Abstract Factory implementation may look similar to Factory Method but the idea there is to create families of objects through factory instances instead of single objects through single methods.
