### ISSUE TITLE
Java 11 support: Build with JDK11

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns#976]
This task is part of the Java 11 transition plan https://github.com/iluwatar/java-design-patterns/wiki/16.-Java-11-Transition

Configure Maven plugins to use Java 11 and verify that build works using JDK11 (see https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/ and https://www.baeldung.com/maven-java-version)

**Comment by iluwatar** [comment]
@lbroman @perwramdemark working on this?

**Comment by lbroman** [comment]
PR #975 should take care of this. Building through the project now, will push the PR in a few minutes.

**Comment by iluwatar** [comment]
This issue no longer needs to be resolved as we are already JDK11 compliant

**Comment by iluwatar** [comment]
Sorry, wrong issue I was editing. Reopened.

**Comment by lbroman** [comment]
In my PR #980 I have left language source and target at 8 for the naked-objects/dom module. This is because java 11 bytecode breaks the datanucleus enhancer, even if they claim that 5.2 should support java 11 bytecode.
I have tried fiddling with the datanucleus dependency versions because the module uses datanucleus core 5 and apis from 4 so I thought that might be the problem. However, bumping up the versions breaks other stuff as they seem to have moved around some classes between 4 and 5.

**Comment by iluwatar** [comment]
I created follow-up task https://github.com/iluwatar/java-design-patterns/issues/983 about the datanucleus issue you described @lbroman. As such I think this issue can be closed. Many thanks for the hard work you've done so far :+1:
